greenmg4/sproject

src/main/java/com/example/demo/controller/CartController.java
=> [박민혁] 장바구니 컨트롤러 수정

front/react/package-lock.json, front/react/package.json, front/react/public/index.html, front/react/src/pages/Cart.jsx, pom.xml, src/main/java/com/example/demo/controller/PaymentController.java
=> [박민혁] 카카오페이 api 연동

front/react/src/pages/Cart.jsx, src/main/java/com/example/demo/controller/CartController.java, src/main/java/com/example/demo/controller/OrderMstController.java, src/main/java/com/example/demo/model/OrderDetailDTO.java, src/main/java/com/example/demo/model/OrderItemDTO.java, src/main/java/com/example/demo/model/OrderMstDTO.java, src/main/java/com/example/demo/model/OrderRequestDTO.java, src/main/java/com/example/demo/service/CartService.java, src/main/java/com/example/demo/service/CartServiceImpl.java, src/main/java/com/example/demo/service/OrderMstService.java, src/main/java/com/example/demo/service/OrderMstServiceImpl.java, src/main/java/mapperInterface/CartMapper.java, src/main/java/mapperInterface/OrderMstMapper.java
=> [박민혁] 결제기능 개발 완료

src/main/java/mapperInterface/OrderMstMapper.java
=> [박민혁] 결제 기능 매퍼 수정

front/react/src/pages/Cart.jsx, src/main/java/mapperInterface/CartMapper.java, src/main/java/mapperInterface/OrderMstMapper.java
=> [박민혁] bug fix

src/main/java/com/example/demo/SprojectApplication.java, src/main/java/mapperInterface/ProductMapper.java
=> [박민혁] 상품 조회 기능 수정

front/react/src/pages/ProductList.css, front/react/src/pages/ProductList.jsx, src/main/java/com/example/demo/model/ProductDTO.java, src/main/java/mapperInterface/ProductMapper.java
[박민혁] 상품 리스트 화면 및 상품 디테일 화면 개발
=> [박민혁] 상품 리스트 화면 및 상품 디테일 화면 개발

front/react/package-lock.json, front/react/package.json, front/react/src/components/Main.jsx, front/react/src/pages/MainDefault.jsx, front/react/src/pages/Statistics/Statistics.jsx, front/react/src/pages/Statistics/StatisticsProd.jsx, front/react/src/pages/Statistics/StatisticsTab.jsx, front/react/src/pages/Statistics/StatisticsYear.jsx, front/react/src/pages/Statistics/StatisticsYearM.jsx, front/react/src/styles/Statistics.css
=> [김후곤]통계 작업

front/react/src/pages/Cart.jsx, src/main/java/com/example/demo/controller/OrderMstController.java, src/main/java/com/example/demo/service/OrderMstServiceImpl.java, src/main/java/mapperInterface/CustMapper.java
[박민혁] 상품 결제시 회원 데이터에 결제금액 업데이트 기능 구현
=> [박민혁] 상품 결제시 회원 데이터에 결제금액 업데이트 기능 구현

front/react/src/components/Header.jsx, front/react/src/pages/OrderPayment.jsx, src/main/java/com/example/demo/controller/OrderMstController.java, src/main/java/com/example/demo/model/GradeDiscDTO.java, src/main/java/com/example/demo/service/OrderMstServiceImpl.java, src/main/java/mapperInterface/CartMapper.java, src/main/java/mapperInterface/CustMapper.java
[박민혁] 결제 할인율 기능 적용 및 헤더 장바구니 스팬 추가
=> [박민혁] 결제 할인율 기능 적용 및 헤더 장바구니 스팬 추가

front/react/src/pages/OrderPayment.jsx, src/main/java/com/example/demo/controller/AddressController.java, src/main/java/com/example/demo/model/AddressDTO.java, src/main/java/com/example/demo/service/AddressService.java, src/main/java/com/example/demo/service/AddressServiceImpl.java, src/main/java/mapperInterface/AddressMapper.java
[박민혁] 결제시 기본주소 호출 기능 및 결제 기능 수정
=> [박민혁] 결제시 기본주소 호출 기능 및 결제 기능 수정

front/react/src/pages/MainDefault.jsx
=> [후곤]추천상품1개일때,더블클릭이벤트추가.

front/react/src/pages/OrderPayment.jsx, src/main/java/com/example/demo/controller/CustController.java
=> [박민혁] 카드사 결제로 결제 변경

front/react/src/pages/Statistics/Statistics.jsx, front/react/src/pages/Statistics/StatisticsProd.jsx, front/react/src/pages/Statistics/StatisticsTab.jsx, front/react/src/pages/Statistics/StatisticsYear.jsx, front/react/src/pages/Statistics/StatisticsYearM.jsx, front/react/src/styles/Statistics.css
=> [후곤]통계 view 사이즈 조정.

front/react/src/pages/UserInfo.jsx, front/react/src/pages/orderList.jsx, src/main/java/com/example/demo/controller/OrderListController.java, src/main/java/com/example/demo/controller/OrderMstController.java, src/main/java/com/example/demo/model/OrderListDTO.java, src/main/java/com/example/demo/service/OrderListService.java, src/main/java/com/example/demo/service/OrderListServiceImpl.java, src/main/java/mapperInterface/OrderListMapper.java
=> [박민혁] 결제 내역 출력

front/react/src/pages/OrderPayment.jsx, front/react/src/pages/orderList.jsx, src/main/java/com/example/demo/controller/OrderListController.java, src/main/java/com/example/demo/controller/OrderMstController.java, src/main/java/com/example/demo/model/OrderListDTO.java, src/main/java/com/example/demo/model/OrderMstDTO.java, src/main/java/com/example/demo/service/OrderListService.java, src/main/java/com/example/demo/service/OrderListServiceImpl.java, src/main/java/com/example/demo/service/OrderMstService.java, src/main/java/com/example/demo/service/OrderMstServiceImpl.java, src/main/java/mapperInterface/OrderListMapper.java, src/main/java/mapperInterface/OrderMstMapper.java
=> [박민혁] 결재 내역 페이지 기능 개발

front/react/src/pages/orderList.jsx, src/main/java/mapperInterface/OrderListMapper.java
=> [박민혁] 결재 내역 화면 변경

front/react/src/pages/UserEdit.jsx, front/react/src/pages/UserInfo.jsx, front/react/src/pages/UserJoin/UserAddress.jsx, front/react/src/pages/UserJoin/UserAddressF.jsx, front/react/src/styles/User/UserAddress.css, front/react/src/styles/User/UserAddressF.css, front/react/src/styles/User/UserInfo.css, src/main/java/com/example/demo/controller/AddressController.java, src/main/java/com/example/demo/controller/UserEditController.java, src/main/java/com/example/demo/model/AddressDTO.java, src/main/java/com/example/demo/model/UserInfoDTO.java, src/main/java/com/example/demo/service/UserInfoService.java, src/main/java/com/example/demo/service/UserInfoServiceImpl.java, src/main/java/mapperInterface/AddressMapper.java, src/main/java/mapperInterface/UserInfoMapper.java, src/main/resources/mappers/AddressMapper.xml, src/main/resources/mappers/UserInfoMapper.xml
=> [HR] 내정보 페이지 CSS 수정

front/react/src/components/ChatRoom/AdminChatRoomList.css, front/react/src/components/ChatRoom/AdminChatRoomList.jsx, front/react/src/components/ChatRoom/ChatRoomList.jsx, front/react/src/components/Main.jsx, src/main/java/com/example/demo/controller/ChatController.java, src/main/java/com/example/demo/service/ChatService.java, src/main/java/com/example/demo/service/ChatServiceImpl.java, src/main/java/mapperInterface/ChatMessageMapper.java, src/main/resources/mappers/ChatMessageMapper.xml
=> [김정민] 어드민전용 ID별 전체채팅 상담내역 추가

front/react/src/pages/orderList.jsx
=> [박민혁] 결제 내역 화면 수정
